server:
  port: 80
#  compression:
#     enabled: true
#     mime-types: text/html,text/xml,text/plain,text/css,application/json,application/javascript,image/svg+xml,application/x-font-ttf,application/x-font-truetype,application/x-font-opentype,application/vnd.ms-fontobject,application/font-sfnt  

spring:
  resources:
    cache:
      period: 31556926
  datasource:
    url: jdbc:h2:./db/mycustomer;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  jpa:
    hibernate.ddl-auto: create
  jackson:
    serialization:
      write-date-timestamps-as-nanoseconds: false
      write-dates-as-timestamps: false
      
logging:
  level:
    org.hibernate: WARN
    org.springframework: WARN
    org.apache: WARN  
    ch: WARN
  file: ./app.log    